# Generated by Django 6.0.3 on 2026-07-19 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('signed', 'Signed'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('signer_name', models.CharField(max_length=255)),
                ('signer_email', models.EmailField(max_length=254)),
                ('signing_order', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True, help_text='Personal message to the signer')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='contracts.contract')),
                ('signer_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.party')),
            ],
            options={
                'ordering': ['signing_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_type', models.CharField(choices=[('drawn', 'Drawn'), ('typed', 'Typed'), ('uploaded', 'Uploaded')], default='typed', max_length=20)),
                ('signature_data', models.TextField(help_text='Base64 encoded signature image or typed signature text')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('signature_hash', models.CharField(blank=True, max_length=128)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='esignatures.signaturerequest')),
            ],
            options={
                'ordering': ['signed_at'],
            },
        ),
        migrations.CreateModel(
            name='SigningAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('request_created', 'Request Created'), ('request_sent', 'Request Sent'), ('document_viewed', 'Document Viewed'), ('signature_started', 'Signature Started'), ('signature_completed', 'Signature Completed'), ('request_completed', 'All Signatures Collected'), ('request_declined', 'Request Declined'), ('request_expired', 'Request Expired')], max_length=30)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='esignatures.signaturerequest')),
            ],
            options={
                'verbose_name_plural': 'Signing audit logs',
                'ordering': ['timestamp'],
            },
        ),
    ]
