# Generated by Django 6.0.3 on 2026-07-19 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='contracts.contract')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parties_involved', models.JSONField(blank=True, default=list)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_terms', models.TextField(blank=True)),
                ('payment_terms', models.TextField(blank=True)),
                ('termination_clauses', models.TextField(blank=True)),
                ('liability_cap', models.CharField(blank=True, max_length=255)),
                ('governing_law', models.CharField(blank=True, max_length=255)),
                ('jurisdiction', models.CharField(blank=True, max_length=255)),
                ('non_compete_clause', models.BooleanField(default=False)),
                ('confidentiality_clause', models.BooleanField(default=False)),
                ('indemnification_clause', models.BooleanField(default=False)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('force_majeure', models.BooleanField(default=False)),
                ('extracted_text_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='ai_analysis.analysisresult')),
            ],
            options={
                'verbose_name_plural': 'Extracted metadata',
            },
        ),
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('category', models.CharField(help_text='Risk category (e.g., Auto-Renewal, Liability)', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('clause_reference', models.TextField(blank=True, help_text='The specific clause text that triggered this flag')),
                ('recommendation', models.TextField(blank=True, help_text='Suggested action to mitigate this risk')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='ai_analysis.analysisresult')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
    ]
